{
 "title": "Analytics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Menu commands",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"events\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bot_commands\" and exists r[\"menu_command\"])\r\n  |> group(columns: [\"menu_command\"])\r\n  |> aggregateWindow(every: 1h, fn: sum)\r\n"
    }
   ]
  },
  {
   "title": "Formatting photo",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"events\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bot_commands\" and exists r[\"formatting\"])\r\n  |> group(columns: [\"user\"])\r\n  |> aggregateWindow(every: 1h, fn: sum)\r\n"
    }
   ]
  },
  {
   "title": "User activity",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"events\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bot_commands\" and exists r[\"user\"])\r\n  |> group(columns: [\"user\"])\r\n  |> aggregateWindow(every: 1h, fn: sum)\r\n\r\n"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "logs",
   "description": "Сообщения от пользователей не являющиеся командами",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"events\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bot_commands\" and exists r[\"flood\"])\r\n  |> group(columns: [\"user\"])\r\n  |> drop(columns: [\"_value\", \"_field\", \"_measurement\"])"
    }
   ]
  }
 ]
}