name: Code checks
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: 'Create env file'
        run: |
          echo "${{ secrets.BOT_SECRET }}" > .env
      - name: Run flake8
        run: flake8
      - name: Run pytest
        run: pytest
