name: Code checks
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: abatilo/actions-poetry@v2
        with:
           poetry-version: 1.4.2
           
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10
          cache: 'poetry'

      - name: 'Create env file'
        run: |
          echo "${{ secrets.BOT_SECRET }}" > .env
      - name: Run flake8
        run: flake8
      - name: Run pytest
        run: pytest
